vich_uploader:
    db_driver: orm

    mappings:
        room:
            uri_prefix: /images/room
            upload_destination: '%kernel.project_dir%/public/images/room'
            namer: vich_uploader.namer_uniqid


            delete_on_update: true
            delete_on_remove: true