vich_uploader:
    db_driver: orm

    mappings:
        room:
            uri_prefix: /images/room
            upload_destination: '%kernel.project_dir%/public/images/room'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true