/*
-- Query: select * from room
LIMIT 0, 1000

-- Date: 2022-10-31 12:29
*/
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (1,'AZUR','bed-g5b5832559-1920.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula',67800,1,1,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (2,'COTE','visualsofdana-t5pl6cien-i-unsplash.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula',67800,1,1,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (3,'LUX','7b16804154c2b6c9c2b39d056ccdfc28413c57cf, jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra',67800,1,1,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (4,'TEZAMI','353def0165b63914366b3e7d9211dc756a933bbf, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, ve',67800,1,1,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (5,'RAGNAR','c7e5bd223c9df1930c6c37a7790e1efb8b1970d4, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, ve',67800,2,2,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (6,'LILO','1ec099f360a1998ea4b789e572a4395bbab1d1da, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, ve',67800,2,2,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (7,'GRAND TSIBILI','7ff7feab99309cc8676b1ae5091b466668c916de, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, ve',67800,2,2,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (8,'ROMLEND','2fa97cbd60a52b5951425b77a98a758ab8da942c, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, ve',67800,3,4,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (9,'NORIO','319cdb3639353ac479561ac24654406c5941a447, jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, ve',67800,3,4,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (10,'NEW CITY','d85e40b364334545524170a2fa759a9edf7792f5, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, ve',67800,3,4,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (11,'MOKO','27b208cd2250a054828334b23d23e0c183ea4632, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,4,5,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (12,'ADEN','c6a21466722c485d5d750289d57648b38cecc108, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,4,5,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (13,'ELEGANT','e8506815fde9f8fa39fa28e421147f72422fbbd8, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,5,6,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (14,'MER','a49dd6c992221c467f8d8f710aa8cf004fa01fc4, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,5,6,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (15,'SABLE','ff75a466fc68f3ec5626cc015624fa24dd547329, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,5,6,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (16,'FIRAS','6142f72f9796220515e9345ac51ec832f24463c8, jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,5,6,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (17,'IVERTUBANI','268b9224a187493e529423663174f8667cb402d0, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,5,6,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (18,'ATU','e16dd649fac06dfb421a7d8a9952513859cad5c6, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,6,7,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (19,'DKS-BRIDGE','d7c8eb50c69439b414e1623d05fe3dc29ff0a6f0, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,6,7,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (20,'SOLEIL','d5ef7d1b8a3697549ec99d5e3d3a67fd24dda534, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,6,7,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (21,'LUNE','f38aee06166b03673d71c44d42e6cd047d87eec5, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,7,8,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (22,'ETOILE','a9f4ecca16c7c491e1a422402c2b89e36e15a27d, webp','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam commodo, massa vel facilisis malesuada, mauris ipsum tempus ipsum, in tristique mi quam at mauris. Duis volutpat ultrices ligula. Pellentesque eget leo sed lacus convallis tristique. Done',67800,7,8,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (23,'URUS','edelle-bruton-pjno2sllbb8-unsplash.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',67800,4,5,0);
INSERT INTO `room` (`id`,`title`,`image`,`description`,`price`,`hostel_id`,`supervisor_id`,`countrooms`) VALUES (24,'RHEMA','hotel-g866b64a96-1920.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non purus ac tortor accumsan malesuada vel vitae augue. Suspendisse lobortis elit a ante facilisis dapibus. Praesent odio leo, finibus at posuere sit amet, varius sit amet ex. Curabitur ultri',67800,1,1,5);
