/*
-- Query: select*from hostel
LIMIT 0, 1000

-- Date: 2022-09-15 23:06
*/
INSERT INTO `` (`id`,`name`,`city`,`address`,`description`) VALUES (1,'Westeen','Nice','49 Rue Ameline, 06000','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, vel facilisis neque. Suspendisse consectetur accumsan felis, id tristique ante semper nec.');
INSERT INTO `` (`id`,`name`,`city`,`address`,`description`) VALUES (2,'Hyatt','PARIS','7 Rue Forest Pass, 75010','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, vel facilisis neque. Suspendisse consectetur accumsan felis, id tristique ante semper nec.');
INSERT INTO `` (`id`,`name`,`city`,`address`,`description`) VALUES (3,'Cap','TOULOUSE','58 Rue St-Etienne, 31100','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, vel facilisis neque. Suspendisse consectetur accumsan felis, id tristique ante semper nec.');
INSERT INTO `` (`id`,`name`,`city`,`address`,`description`) VALUES (4,'Ibis','LYON','26 Rue Daguenille, 69000','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, vel facilisis neque. Suspendisse consectetur accumsan felis, id tristique ante semper nec.');
INSERT INTO `` (`id`,`name`,`city`,`address`,`description`) VALUES (5,'Hotel V','POITIERS','74 Rue Estesse, 86000','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, vel facilisis neque. Suspendisse consectetur accumsan felis, id tristique ante semper nec.');
INSERT INTO `` (`id`,`name`,`city`,`address`,`description`) VALUES (6,'Jazzy','BORDEAUX','3 Rue Soritel, 33300','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, vel facilisis neque. Suspendisse consectetur accumsan felis, id tristique ante semper nec.');
INSERT INTO `` (`id`,`name`,`city`,`address`,`description`) VALUES (7,'Yadel','STRASBOURG','57 Rue Firatome, 67000','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac feugiat tellus. Vivamus sodales accumsan sapien, a sollicitudin est dapibus nec. Etiam massa sapien, posuere bibendum pharetra et, blandit in ligula. Suspendisse ut tincidunt nulla, vel facilisis neque. Suspendisse consectetur accumsan felis, id tristique ante semper nec.');
